### ISSUE TITLE
use "deno bundle" with git integration

### ISSUE THREAD

**Issue by christianhaller** [TooTallNate/vercel-deno#21]
Hi Nathan,
I try to `deno bundle` my api code into a single file.
It's working locally, but not with the git integration.

First, I discovered that the `npm run build` failed with `command not found: deno`.
The binary seems not yet there.
After installing it manually (https://www.npmjs.com/package/@christianhaller/npm-deno) it was building.
But it was failing, when there was no placeholder like an empty `index.js` in the `api` directory.

https://vercel.com/christianhaller/download-your-travelmap/5g7m2ms4m

My code: https://github.com/christianhaller/download-your-travelmap

In the vercel docs I found a config property named `includedFiles`. https://vercel.com/docs/configuration#project/functions
Do you think you will support this?

My workaround is to checkin a locally bundled file.

**Comment by TooTallNate** [comment]
Hey there Christian, thanks for the detailed issue.

Firstly, you don't need to run `deno bundle` - this Runtime takes care of the file bundling at build-time (using `deno cache`, not `bundle`). It also takes care of downloading the `deno` binary, so your `npm-deno` dep is not necessary.

Secondly, the `npm run build` step is executed implicitly by Vercel to build your _frontend_ code (i.e. static HTML files) in a different build context than the one your Deno API endpoint will be built in. This Runtime does not execute any `npm` scripts. In fact, it doesn't seem like your project should have a `package.json` file at all since there is already a `public` directory.

Finally, the entrypoint to your API function needs to be within the `api` directory. Seems like the `src/index.ts` file should be located at `api/index.ts` and the import paths corrected.

I've created a pull-request that builds correctly: https://github.com/christianhaller/download-your-travelmap/pull/195

Hope that helps!

**Comment by christianhaller** [comment]
Fantastic! Thank you very much for your patience and your detailed explanation. That helped me a lot! And thank you for the PR.
Without a package.json, it feels a little bit naked, but I works the way you explained!

Thanks a lot! 💯

**Comment by TooTallNate** [comment]
You can definitely still have a `package.json` file for your frontend code (for example, this repo has Next.js configured), but understand that the`vercel-deno` Runtime does not rely on this file in any way.
