### ISSUE TITLE
Not able to use the example --> getting import error

### ISSUE THREAD

**Issue by ajerni** [TooTallNate/vercel-deno#5]
```
NowBuildError: api/hellodeno.ts(1,31): error TS2691: An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std@0.52.0/http/server' instead.
```

**Comment by TooTallNate** [comment]
I don't think you are properly configuring this Runtime. This error seems to be coming from `@vercel/node` Runtime.

Can you share with me your `vercel.json` file?

**Comment by ajerni** [comment]
My mistake was to have the verce.json within the api folder. Now when I moved it to the rood directory it works. Very cool stuff, thank you! Please update the readme with the latest version of the vercel.json.

**Comment by ajerni** [comment]
How can I run this on vercel? Need to export something?
```
import { Application } from "https://deno.land/x/oak@v5.2.0/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
  console.log(ctx);
  ctx.
});

await app.listen({ port: 8000 });
```

**Comment by TooTallNate** [comment]
Hi @ajerni, I took a look at "oak" and unfortunately it's not currently possible. However, I did come up with a [solution](https://github.com/oakserver/oak/pull/173) and [added a demo API endpoint](https://github.com/TooTallNate/vercel-deno/blob/741192315438a39b77669907f93f39e2063d786b/api/oak.ts) ([Live Example](https://vercel-deno-jqo1qfrtw.vercel.app/api/oak)), which is easy since in Deno, I can just point to my fork 😄.

Let me know what you think!

**Comment by ajerni** [comment]
Hi @TooTallNate, that's great! Thanks a lot for your help and the implementation and the PR at oakserver. I think this is a real benefit and motivates me to learn Deno. I just wanted to test if I could easyle deploy it somewhere and vercel is amazing! I do not want to mess arround with Docker and anything and what you provide here seems to be a perfect ready to go solution for me.
