### ISSUE TITLE
Using abc with vercel-deno

### ISSUE THREAD

**Issue by omar2205** [TooTallNate/vercel-deno#53]
Is there an example of using [abc](https://deno.land/x/abc@v1)?

**Comment by TooTallNate** [comment]
The problem (and it seems a lot of Deno frameworks are guilty of this) with `abc` is that it [implements the `for…of` loop](https://github.com/zhmushan/abc/blob/3737213fedf853014dd15fdd15f8bc1ca38cd047/app.ts#L52-L74) of the HTTP server and does not expose a function to handle a single HTTP request.

`abc` needs to be adjusted to expose a function that can handle a single HTTP request, so that it can be exported by the serverless function file. Similar to [this PR](https://github.com/oakserver/oak/pull/173) which made `oak` framework be compatible.

**Comment by TooTallNate** [comment]
Gonna close since this isn't an issue with `vercel-deno` itself. Happy to add an example for abc to the `api` directory if/when they add a single request handler function.
