### ISSUE TITLE
Obtaining full URL of request

### ISSUE THREAD

**Issue by jsejcksn** [TooTallNate/vercel-deno#57]
Hi @TooTallNate:

Is there a simpler way than the commented line below to get the URL of each request?

```ts
import type {ServerRequest} from 'https://deno.land/std@0.87.0/http/server.ts';

export default async (req: ServerRequest): Promise<void> => {
  const url = new URL(`https://${Deno.env.get('VERCEL_URL')}${req.url}`); // 👈
  // ...
};
```

Aside (general question): I didn't see it documented anywhere, but I'm guessing that the runtime executes the code with [all permissions](https://deno.land/manual@v1.7.4/getting_started/permissions) since a permissions error isn't thrown about lack of access to environment or network. Is that the case?

**Comment by TooTallNate** [comment]
This is, I believe, the most reliable way to construct the full URL: https://github.com/TooTallNate/vercel-deno/blob/c0af678a6ae71bd837edcb64c899977d29340333/api/dump.ts#L51-L52

```typescript
	const base = `${req.headers.get('x-forwarded-proto')}://${req.headers.get('x-forwarded-host')}`;
	const url = new URL(req.url, base);
```

And yes to your other question: the lambda is invoked with `deno run --allow-all` permissions. This is ok because it's already running in a sanboxed environment. See [the source code](https://github.com/TooTallNate/vercel-deno/blob/c0af678a6ae71bd837edcb64c899977d29340333/src/bootstrap#L24) as well.
